/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as ReportTypeRouteImport } from './routes/report.$type'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStopRouteImport } from './routes/_authenticated/stop'
import { Route as AuthenticatedMosRouteImport } from './routes/_authenticated/mos'
import { Route as AuthenticatedMeldingenRouteImport } from './routes/_authenticated/meldingen'
import { Route as AuthenticatedInspectiesRouteImport } from './routes/_authenticated/inspecties'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedToolboxesIndexRouteImport } from './routes/_authenticated/toolboxes.index'
import { Route as AuthenticatedInspectiesIndexRouteImport } from './routes/_authenticated/inspecties.index'
import { Route as ApiPublicToolboxSignRouteImport } from './routes/api/public/toolbox-sign'
import { Route as AuthenticatedToolboxesNewRouteImport } from './routes/_authenticated/toolboxes.new'
import { Route as AuthenticatedToolboxesIdRouteImport } from './routes/_authenticated/toolboxes.$id'
import { Route as AuthenticatedInspectiesWpiRouteImport } from './routes/_authenticated/inspecties.wpi'
import { Route as AuthenticatedInspectiesKwaliteitRouteImport } from './routes/_authenticated/inspecties.kwaliteit'
import { Route as AuthenticatedToolboxesSessionsIdRouteImport } from './routes/_authenticated/toolboxes.sessions.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTypeRoute = ReportTypeRouteImport.update({
  id: '/report/$type',
  path: '/report/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStopRoute = AuthenticatedStopRouteImport.update({
  id: '/stop',
  path: '/stop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMosRoute = AuthenticatedMosRouteImport.update({
  id: '/mos',
  path: '/mos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeldingenRoute = AuthenticatedMeldingenRouteImport.update({
  id: '/meldingen',
  path: '/meldingen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectiesRoute = AuthenticatedInspectiesRouteImport.update({
  id: '/inspecties',
  path: '/inspecties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolboxesIndexRoute =
  AuthenticatedToolboxesIndexRouteImport.update({
    id: '/toolboxes/',
    path: '/toolboxes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectiesIndexRoute =
  AuthenticatedInspectiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInspectiesRoute,
  } as any)
const ApiPublicToolboxSignRoute = ApiPublicToolboxSignRouteImport.update({
  id: '/api/public/toolbox-sign',
  path: '/api/public/toolbox-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolboxesNewRoute =
  AuthenticatedToolboxesNewRouteImport.update({
    id: '/toolboxes/new',
    path: '/toolboxes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolboxesIdRoute =
  AuthenticatedToolboxesIdRouteImport.update({
    id: '/toolboxes/$id',
    path: '/toolboxes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectiesWpiRoute =
  AuthenticatedInspectiesWpiRouteImport.update({
    id: '/wpi',
    path: '/wpi',
    getParentRoute: () => AuthenticatedInspectiesRoute,
  } as any)
const AuthenticatedInspectiesKwaliteitRoute =
  AuthenticatedInspectiesKwaliteitRouteImport.update({
    id: '/kwaliteit',
    path: '/kwaliteit',
    getParentRoute: () => AuthenticatedInspectiesRoute,
  } as any)
const AuthenticatedToolboxesSessionsIdRoute =
  AuthenticatedToolboxesSessionsIdRouteImport.update({
    id: '/toolboxes/sessions/$id',
    path: '/toolboxes/sessions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/inspecties': typeof AuthenticatedInspectiesRouteWithChildren
  '/meldingen': typeof AuthenticatedMeldingenRoute
  '/mos': typeof AuthenticatedMosRoute
  '/stop': typeof AuthenticatedStopRoute
  '/users': typeof AuthenticatedUsersRoute
  '/report/$type': typeof ReportTypeRoute
  '/sign/$token': typeof SignTokenRoute
  '/inspecties/kwaliteit': typeof AuthenticatedInspectiesKwaliteitRoute
  '/inspecties/wpi': typeof AuthenticatedInspectiesWpiRoute
  '/toolboxes/$id': typeof AuthenticatedToolboxesIdRoute
  '/toolboxes/new': typeof AuthenticatedToolboxesNewRoute
  '/api/public/toolbox-sign': typeof ApiPublicToolboxSignRoute
  '/inspecties/': typeof AuthenticatedInspectiesIndexRoute
  '/toolboxes/': typeof AuthenticatedToolboxesIndexRoute
  '/toolboxes/sessions/$id': typeof AuthenticatedToolboxesSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/meldingen': typeof AuthenticatedMeldingenRoute
  '/mos': typeof AuthenticatedMosRoute
  '/stop': typeof AuthenticatedStopRoute
  '/users': typeof AuthenticatedUsersRoute
  '/report/$type': typeof ReportTypeRoute
  '/sign/$token': typeof SignTokenRoute
  '/inspecties/kwaliteit': typeof AuthenticatedInspectiesKwaliteitRoute
  '/inspecties/wpi': typeof AuthenticatedInspectiesWpiRoute
  '/toolboxes/$id': typeof AuthenticatedToolboxesIdRoute
  '/toolboxes/new': typeof AuthenticatedToolboxesNewRoute
  '/api/public/toolbox-sign': typeof ApiPublicToolboxSignRoute
  '/inspecties': typeof AuthenticatedInspectiesIndexRoute
  '/toolboxes': typeof AuthenticatedToolboxesIndexRoute
  '/toolboxes/sessions/$id': typeof AuthenticatedToolboxesSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/inspecties': typeof AuthenticatedInspectiesRouteWithChildren
  '/_authenticated/meldingen': typeof AuthenticatedMeldingenRoute
  '/_authenticated/mos': typeof AuthenticatedMosRoute
  '/_authenticated/stop': typeof AuthenticatedStopRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/report/$type': typeof ReportTypeRoute
  '/sign/$token': typeof SignTokenRoute
  '/_authenticated/inspecties/kwaliteit': typeof AuthenticatedInspectiesKwaliteitRoute
  '/_authenticated/inspecties/wpi': typeof AuthenticatedInspectiesWpiRoute
  '/_authenticated/toolboxes/$id': typeof AuthenticatedToolboxesIdRoute
  '/_authenticated/toolboxes/new': typeof AuthenticatedToolboxesNewRoute
  '/api/public/toolbox-sign': typeof ApiPublicToolboxSignRoute
  '/_authenticated/inspecties/': typeof AuthenticatedInspectiesIndexRoute
  '/_authenticated/toolboxes/': typeof AuthenticatedToolboxesIndexRoute
  '/_authenticated/toolboxes/sessions/$id': typeof AuthenticatedToolboxesSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/employees'
    | '/inspecties'
    | '/meldingen'
    | '/mos'
    | '/stop'
    | '/users'
    | '/report/$type'
    | '/sign/$token'
    | '/inspecties/kwaliteit'
    | '/inspecties/wpi'
    | '/toolboxes/$id'
    | '/toolboxes/new'
    | '/api/public/toolbox-sign'
    | '/inspecties/'
    | '/toolboxes/'
    | '/toolboxes/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/employees'
    | '/meldingen'
    | '/mos'
    | '/stop'
    | '/users'
    | '/report/$type'
    | '/sign/$token'
    | '/inspecties/kwaliteit'
    | '/inspecties/wpi'
    | '/toolboxes/$id'
    | '/toolboxes/new'
    | '/api/public/toolbox-sign'
    | '/inspecties'
    | '/toolboxes'
    | '/toolboxes/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/inspecties'
    | '/_authenticated/meldingen'
    | '/_authenticated/mos'
    | '/_authenticated/stop'
    | '/_authenticated/users'
    | '/report/$type'
    | '/sign/$token'
    | '/_authenticated/inspecties/kwaliteit'
    | '/_authenticated/inspecties/wpi'
    | '/_authenticated/toolboxes/$id'
    | '/_authenticated/toolboxes/new'
    | '/api/public/toolbox-sign'
    | '/_authenticated/inspecties/'
    | '/_authenticated/toolboxes/'
    | '/_authenticated/toolboxes/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ReportTypeRoute: typeof ReportTypeRoute
  SignTokenRoute: typeof SignTokenRoute
  ApiPublicToolboxSignRoute: typeof ApiPublicToolboxSignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$type': {
      id: '/report/$type'
      path: '/report/$type'
      fullPath: '/report/$type'
      preLoaderRoute: typeof ReportTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stop': {
      id: '/_authenticated/stop'
      path: '/stop'
      fullPath: '/stop'
      preLoaderRoute: typeof AuthenticatedStopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mos': {
      id: '/_authenticated/mos'
      path: '/mos'
      fullPath: '/mos'
      preLoaderRoute: typeof AuthenticatedMosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldingen': {
      id: '/_authenticated/meldingen'
      path: '/meldingen'
      fullPath: '/meldingen'
      preLoaderRoute: typeof AuthenticatedMeldingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspecties': {
      id: '/_authenticated/inspecties'
      path: '/inspecties'
      fullPath: '/inspecties'
      preLoaderRoute: typeof AuthenticatedInspectiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/toolboxes/': {
      id: '/_authenticated/toolboxes/'
      path: '/toolboxes'
      fullPath: '/toolboxes/'
      preLoaderRoute: typeof AuthenticatedToolboxesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspecties/': {
      id: '/_authenticated/inspecties/'
      path: '/'
      fullPath: '/inspecties/'
      preLoaderRoute: typeof AuthenticatedInspectiesIndexRouteImport
      parentRoute: typeof AuthenticatedInspectiesRoute
    }
    '/api/public/toolbox-sign': {
      id: '/api/public/toolbox-sign'
      path: '/api/public/toolbox-sign'
      fullPath: '/api/public/toolbox-sign'
      preLoaderRoute: typeof ApiPublicToolboxSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/toolboxes/new': {
      id: '/_authenticated/toolboxes/new'
      path: '/toolboxes/new'
      fullPath: '/toolboxes/new'
      preLoaderRoute: typeof AuthenticatedToolboxesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/toolboxes/$id': {
      id: '/_authenticated/toolboxes/$id'
      path: '/toolboxes/$id'
      fullPath: '/toolboxes/$id'
      preLoaderRoute: typeof AuthenticatedToolboxesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspecties/wpi': {
      id: '/_authenticated/inspecties/wpi'
      path: '/wpi'
      fullPath: '/inspecties/wpi'
      preLoaderRoute: typeof AuthenticatedInspectiesWpiRouteImport
      parentRoute: typeof AuthenticatedInspectiesRoute
    }
    '/_authenticated/inspecties/kwaliteit': {
      id: '/_authenticated/inspecties/kwaliteit'
      path: '/kwaliteit'
      fullPath: '/inspecties/kwaliteit'
      preLoaderRoute: typeof AuthenticatedInspectiesKwaliteitRouteImport
      parentRoute: typeof AuthenticatedInspectiesRoute
    }
    '/_authenticated/toolboxes/sessions/$id': {
      id: '/_authenticated/toolboxes/sessions/$id'
      path: '/toolboxes/sessions/$id'
      fullPath: '/toolboxes/sessions/$id'
      preLoaderRoute: typeof AuthenticatedToolboxesSessionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedInspectiesRouteChildren {
  AuthenticatedInspectiesKwaliteitRoute: typeof AuthenticatedInspectiesKwaliteitRoute
  AuthenticatedInspectiesWpiRoute: typeof AuthenticatedInspectiesWpiRoute
  AuthenticatedInspectiesIndexRoute: typeof AuthenticatedInspectiesIndexRoute
}

const AuthenticatedInspectiesRouteChildren: AuthenticatedInspectiesRouteChildren =
  {
    AuthenticatedInspectiesKwaliteitRoute:
      AuthenticatedInspectiesKwaliteitRoute,
    AuthenticatedInspectiesWpiRoute: AuthenticatedInspectiesWpiRoute,
    AuthenticatedInspectiesIndexRoute: AuthenticatedInspectiesIndexRoute,
  }

const AuthenticatedInspectiesRouteWithChildren =
  AuthenticatedInspectiesRoute._addFileChildren(
    AuthenticatedInspectiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedInspectiesRoute: typeof AuthenticatedInspectiesRouteWithChildren
  AuthenticatedMeldingenRoute: typeof AuthenticatedMeldingenRoute
  AuthenticatedMosRoute: typeof AuthenticatedMosRoute
  AuthenticatedStopRoute: typeof AuthenticatedStopRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedToolboxesIdRoute: typeof AuthenticatedToolboxesIdRoute
  AuthenticatedToolboxesNewRoute: typeof AuthenticatedToolboxesNewRoute
  AuthenticatedToolboxesIndexRoute: typeof AuthenticatedToolboxesIndexRoute
  AuthenticatedToolboxesSessionsIdRoute: typeof AuthenticatedToolboxesSessionsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedInspectiesRoute: AuthenticatedInspectiesRouteWithChildren,
  AuthenticatedMeldingenRoute: AuthenticatedMeldingenRoute,
  AuthenticatedMosRoute: AuthenticatedMosRoute,
  AuthenticatedStopRoute: AuthenticatedStopRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedToolboxesIdRoute: AuthenticatedToolboxesIdRoute,
  AuthenticatedToolboxesNewRoute: AuthenticatedToolboxesNewRoute,
  AuthenticatedToolboxesIndexRoute: AuthenticatedToolboxesIndexRoute,
  AuthenticatedToolboxesSessionsIdRoute: AuthenticatedToolboxesSessionsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ReportTypeRoute: ReportTypeRoute,
  SignTokenRoute: SignTokenRoute,
  ApiPublicToolboxSignRoute: ApiPublicToolboxSignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
