/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStopRouteImport } from './routes/_authenticated/stop'
import { Route as AuthenticatedMosRouteImport } from './routes/_authenticated/mos'
import { Route as AuthenticatedMeldingenRouteImport } from './routes/_authenticated/meldingen'
import { Route as AuthenticatedInspectiesRouteImport } from './routes/_authenticated/inspecties'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedToolboxesIndexRouteImport } from './routes/_authenticated/toolboxes.index'
import { Route as AuthenticatedMeldingenIndexRouteImport } from './routes/_authenticated/meldingen.index'
import { Route as AuthenticatedInspectiesIndexRouteImport } from './routes/_authenticated/inspecties.index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees.index'
import { Route as ApiPublicToolboxSignRouteImport } from './routes/api/public/toolbox-sign'
import { Route as AuthenticatedToolboxesNewRouteImport } from './routes/_authenticated/toolboxes.new'
import { Route as AuthenticatedToolboxesIdRouteImport } from './routes/_authenticated/toolboxes.$id'
import { Route as AuthenticatedMeldingenOngevallenRouteImport } from './routes/_authenticated/meldingen.ongevallen'
import { Route as AuthenticatedMeldingenInternRouteImport } from './routes/_authenticated/meldingen.intern'
import { Route as AuthenticatedMeldingenIdRouteImport } from './routes/_authenticated/meldingen.$id'
import { Route as AuthenticatedInspectiesWpiRouteImport } from './routes/_authenticated/inspecties.wpi'
import { Route as AuthenticatedInspectiesKwaliteitRouteImport } from './routes/_authenticated/inspecties.kwaliteit'
import { Route as AuthenticatedInspectiesIdRouteImport } from './routes/_authenticated/inspecties.$id'
import { Route as AuthenticatedEmployeesIdRouteImport } from './routes/_authenticated/employees.$id'
import { Route as AuthenticatedToolboxesSessionsIdRouteImport } from './routes/_authenticated/toolboxes.sessions.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStopRoute = AuthenticatedStopRouteImport.update({
  id: '/stop',
  path: '/stop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMosRoute = AuthenticatedMosRouteImport.update({
  id: '/mos',
  path: '/mos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeldingenRoute = AuthenticatedMeldingenRouteImport.update({
  id: '/meldingen',
  path: '/meldingen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectiesRoute = AuthenticatedInspectiesRouteImport.update({
  id: '/inspecties',
  path: '/inspecties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolboxesIndexRoute =
  AuthenticatedToolboxesIndexRouteImport.update({
    id: '/toolboxes/',
    path: '/toolboxes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeldingenIndexRoute =
  AuthenticatedMeldingenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMeldingenRoute,
  } as any)
const AuthenticatedInspectiesIndexRoute =
  AuthenticatedInspectiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInspectiesRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicToolboxSignRoute = ApiPublicToolboxSignRouteImport.update({
  id: '/api/public/toolbox-sign',
  path: '/api/public/toolbox-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolboxesNewRoute =
  AuthenticatedToolboxesNewRouteImport.update({
    id: '/toolboxes/new',
    path: '/toolboxes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolboxesIdRoute =
  AuthenticatedToolboxesIdRouteImport.update({
    id: '/toolboxes/$id',
    path: '/toolboxes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeldingenOngevallenRoute =
  AuthenticatedMeldingenOngevallenRouteImport.update({
    id: '/ongevallen',
    path: '/ongevallen',
    getParentRoute: () => AuthenticatedMeldingenRoute,
  } as any)
const AuthenticatedMeldingenInternRoute =
  AuthenticatedMeldingenInternRouteImport.update({
    id: '/intern',
    path: '/intern',
    getParentRoute: () => AuthenticatedMeldingenRoute,
  } as any)
const AuthenticatedMeldingenIdRoute =
  AuthenticatedMeldingenIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMeldingenRoute,
  } as any)
const AuthenticatedInspectiesWpiRoute =
  AuthenticatedInspectiesWpiRouteImport.update({
    id: '/wpi',
    path: '/wpi',
    getParentRoute: () => AuthenticatedInspectiesRoute,
  } as any)
const AuthenticatedInspectiesKwaliteitRoute =
  AuthenticatedInspectiesKwaliteitRouteImport.update({
    id: '/kwaliteit',
    path: '/kwaliteit',
    getParentRoute: () => AuthenticatedInspectiesRoute,
  } as any)
const AuthenticatedInspectiesIdRoute =
  AuthenticatedInspectiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedInspectiesRoute,
  } as any)
const AuthenticatedEmployeesIdRoute =
  AuthenticatedEmployeesIdRouteImport.update({
    id: '/employees/$id',
    path: '/employees/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolboxesSessionsIdRoute =
  AuthenticatedToolboxesSessionsIdRouteImport.update({
    id: '/toolboxes/sessions/$id',
    path: '/toolboxes/sessions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/inspecties': typeof AuthenticatedInspectiesRouteWithChildren
  '/meldingen': typeof AuthenticatedMeldingenRouteWithChildren
  '/mos': typeof AuthenticatedMosRoute
  '/stop': typeof AuthenticatedStopRoute
  '/users': typeof AuthenticatedUsersRoute
  '/sign/$token': typeof SignTokenRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/inspecties/$id': typeof AuthenticatedInspectiesIdRoute
  '/inspecties/kwaliteit': typeof AuthenticatedInspectiesKwaliteitRoute
  '/inspecties/wpi': typeof AuthenticatedInspectiesWpiRoute
  '/meldingen/$id': typeof AuthenticatedMeldingenIdRoute
  '/meldingen/intern': typeof AuthenticatedMeldingenInternRoute
  '/meldingen/ongevallen': typeof AuthenticatedMeldingenOngevallenRoute
  '/toolboxes/$id': typeof AuthenticatedToolboxesIdRoute
  '/toolboxes/new': typeof AuthenticatedToolboxesNewRoute
  '/api/public/toolbox-sign': typeof ApiPublicToolboxSignRoute
  '/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/inspecties/': typeof AuthenticatedInspectiesIndexRoute
  '/meldingen/': typeof AuthenticatedMeldingenIndexRoute
  '/toolboxes/': typeof AuthenticatedToolboxesIndexRoute
  '/toolboxes/sessions/$id': typeof AuthenticatedToolboxesSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/mos': typeof AuthenticatedMosRoute
  '/stop': typeof AuthenticatedStopRoute
  '/users': typeof AuthenticatedUsersRoute
  '/sign/$token': typeof SignTokenRoute
  '/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/inspecties/$id': typeof AuthenticatedInspectiesIdRoute
  '/inspecties/kwaliteit': typeof AuthenticatedInspectiesKwaliteitRoute
  '/inspecties/wpi': typeof AuthenticatedInspectiesWpiRoute
  '/meldingen/$id': typeof AuthenticatedMeldingenIdRoute
  '/meldingen/intern': typeof AuthenticatedMeldingenInternRoute
  '/meldingen/ongevallen': typeof AuthenticatedMeldingenOngevallenRoute
  '/toolboxes/$id': typeof AuthenticatedToolboxesIdRoute
  '/toolboxes/new': typeof AuthenticatedToolboxesNewRoute
  '/api/public/toolbox-sign': typeof ApiPublicToolboxSignRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/inspecties': typeof AuthenticatedInspectiesIndexRoute
  '/meldingen': typeof AuthenticatedMeldingenIndexRoute
  '/toolboxes': typeof AuthenticatedToolboxesIndexRoute
  '/toolboxes/sessions/$id': typeof AuthenticatedToolboxesSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/inspecties': typeof AuthenticatedInspectiesRouteWithChildren
  '/_authenticated/meldingen': typeof AuthenticatedMeldingenRouteWithChildren
  '/_authenticated/mos': typeof AuthenticatedMosRoute
  '/_authenticated/stop': typeof AuthenticatedStopRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/sign/$token': typeof SignTokenRoute
  '/_authenticated/employees/$id': typeof AuthenticatedEmployeesIdRoute
  '/_authenticated/inspecties/$id': typeof AuthenticatedInspectiesIdRoute
  '/_authenticated/inspecties/kwaliteit': typeof AuthenticatedInspectiesKwaliteitRoute
  '/_authenticated/inspecties/wpi': typeof AuthenticatedInspectiesWpiRoute
  '/_authenticated/meldingen/$id': typeof AuthenticatedMeldingenIdRoute
  '/_authenticated/meldingen/intern': typeof AuthenticatedMeldingenInternRoute
  '/_authenticated/meldingen/ongevallen': typeof AuthenticatedMeldingenOngevallenRoute
  '/_authenticated/toolboxes/$id': typeof AuthenticatedToolboxesIdRoute
  '/_authenticated/toolboxes/new': typeof AuthenticatedToolboxesNewRoute
  '/api/public/toolbox-sign': typeof ApiPublicToolboxSignRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/inspecties/': typeof AuthenticatedInspectiesIndexRoute
  '/_authenticated/meldingen/': typeof AuthenticatedMeldingenIndexRoute
  '/_authenticated/toolboxes/': typeof AuthenticatedToolboxesIndexRoute
  '/_authenticated/toolboxes/sessions/$id': typeof AuthenticatedToolboxesSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/drafts'
    | '/inspecties'
    | '/meldingen'
    | '/mos'
    | '/stop'
    | '/users'
    | '/sign/$token'
    | '/employees/$id'
    | '/inspecties/$id'
    | '/inspecties/kwaliteit'
    | '/inspecties/wpi'
    | '/meldingen/$id'
    | '/meldingen/intern'
    | '/meldingen/ongevallen'
    | '/toolboxes/$id'
    | '/toolboxes/new'
    | '/api/public/toolbox-sign'
    | '/employees/'
    | '/inspecties/'
    | '/meldingen/'
    | '/toolboxes/'
    | '/toolboxes/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/drafts'
    | '/mos'
    | '/stop'
    | '/users'
    | '/sign/$token'
    | '/employees/$id'
    | '/inspecties/$id'
    | '/inspecties/kwaliteit'
    | '/inspecties/wpi'
    | '/meldingen/$id'
    | '/meldingen/intern'
    | '/meldingen/ongevallen'
    | '/toolboxes/$id'
    | '/toolboxes/new'
    | '/api/public/toolbox-sign'
    | '/employees'
    | '/inspecties'
    | '/meldingen'
    | '/toolboxes'
    | '/toolboxes/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/drafts'
    | '/_authenticated/inspecties'
    | '/_authenticated/meldingen'
    | '/_authenticated/mos'
    | '/_authenticated/stop'
    | '/_authenticated/users'
    | '/sign/$token'
    | '/_authenticated/employees/$id'
    | '/_authenticated/inspecties/$id'
    | '/_authenticated/inspecties/kwaliteit'
    | '/_authenticated/inspecties/wpi'
    | '/_authenticated/meldingen/$id'
    | '/_authenticated/meldingen/intern'
    | '/_authenticated/meldingen/ongevallen'
    | '/_authenticated/toolboxes/$id'
    | '/_authenticated/toolboxes/new'
    | '/api/public/toolbox-sign'
    | '/_authenticated/employees/'
    | '/_authenticated/inspecties/'
    | '/_authenticated/meldingen/'
    | '/_authenticated/toolboxes/'
    | '/_authenticated/toolboxes/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SignTokenRoute: typeof SignTokenRoute
  ApiPublicToolboxSignRoute: typeof ApiPublicToolboxSignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stop': {
      id: '/_authenticated/stop'
      path: '/stop'
      fullPath: '/stop'
      preLoaderRoute: typeof AuthenticatedStopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mos': {
      id: '/_authenticated/mos'
      path: '/mos'
      fullPath: '/mos'
      preLoaderRoute: typeof AuthenticatedMosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldingen': {
      id: '/_authenticated/meldingen'
      path: '/meldingen'
      fullPath: '/meldingen'
      preLoaderRoute: typeof AuthenticatedMeldingenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspecties': {
      id: '/_authenticated/inspecties'
      path: '/inspecties'
      fullPath: '/inspecties'
      preLoaderRoute: typeof AuthenticatedInspectiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/toolboxes/': {
      id: '/_authenticated/toolboxes/'
      path: '/toolboxes'
      fullPath: '/toolboxes/'
      preLoaderRoute: typeof AuthenticatedToolboxesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldingen/': {
      id: '/_authenticated/meldingen/'
      path: '/'
      fullPath: '/meldingen/'
      preLoaderRoute: typeof AuthenticatedMeldingenIndexRouteImport
      parentRoute: typeof AuthenticatedMeldingenRoute
    }
    '/_authenticated/inspecties/': {
      id: '/_authenticated/inspecties/'
      path: '/'
      fullPath: '/inspecties/'
      preLoaderRoute: typeof AuthenticatedInspectiesIndexRouteImport
      parentRoute: typeof AuthenticatedInspectiesRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/toolbox-sign': {
      id: '/api/public/toolbox-sign'
      path: '/api/public/toolbox-sign'
      fullPath: '/api/public/toolbox-sign'
      preLoaderRoute: typeof ApiPublicToolboxSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/toolboxes/new': {
      id: '/_authenticated/toolboxes/new'
      path: '/toolboxes/new'
      fullPath: '/toolboxes/new'
      preLoaderRoute: typeof AuthenticatedToolboxesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/toolboxes/$id': {
      id: '/_authenticated/toolboxes/$id'
      path: '/toolboxes/$id'
      fullPath: '/toolboxes/$id'
      preLoaderRoute: typeof AuthenticatedToolboxesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldingen/ongevallen': {
      id: '/_authenticated/meldingen/ongevallen'
      path: '/ongevallen'
      fullPath: '/meldingen/ongevallen'
      preLoaderRoute: typeof AuthenticatedMeldingenOngevallenRouteImport
      parentRoute: typeof AuthenticatedMeldingenRoute
    }
    '/_authenticated/meldingen/intern': {
      id: '/_authenticated/meldingen/intern'
      path: '/intern'
      fullPath: '/meldingen/intern'
      preLoaderRoute: typeof AuthenticatedMeldingenInternRouteImport
      parentRoute: typeof AuthenticatedMeldingenRoute
    }
    '/_authenticated/meldingen/$id': {
      id: '/_authenticated/meldingen/$id'
      path: '/$id'
      fullPath: '/meldingen/$id'
      preLoaderRoute: typeof AuthenticatedMeldingenIdRouteImport
      parentRoute: typeof AuthenticatedMeldingenRoute
    }
    '/_authenticated/inspecties/wpi': {
      id: '/_authenticated/inspecties/wpi'
      path: '/wpi'
      fullPath: '/inspecties/wpi'
      preLoaderRoute: typeof AuthenticatedInspectiesWpiRouteImport
      parentRoute: typeof AuthenticatedInspectiesRoute
    }
    '/_authenticated/inspecties/kwaliteit': {
      id: '/_authenticated/inspecties/kwaliteit'
      path: '/kwaliteit'
      fullPath: '/inspecties/kwaliteit'
      preLoaderRoute: typeof AuthenticatedInspectiesKwaliteitRouteImport
      parentRoute: typeof AuthenticatedInspectiesRoute
    }
    '/_authenticated/inspecties/$id': {
      id: '/_authenticated/inspecties/$id'
      path: '/$id'
      fullPath: '/inspecties/$id'
      preLoaderRoute: typeof AuthenticatedInspectiesIdRouteImport
      parentRoute: typeof AuthenticatedInspectiesRoute
    }
    '/_authenticated/employees/$id': {
      id: '/_authenticated/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AuthenticatedEmployeesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/toolboxes/sessions/$id': {
      id: '/_authenticated/toolboxes/sessions/$id'
      path: '/toolboxes/sessions/$id'
      fullPath: '/toolboxes/sessions/$id'
      preLoaderRoute: typeof AuthenticatedToolboxesSessionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedInspectiesRouteChildren {
  AuthenticatedInspectiesIdRoute: typeof AuthenticatedInspectiesIdRoute
  AuthenticatedInspectiesKwaliteitRoute: typeof AuthenticatedInspectiesKwaliteitRoute
  AuthenticatedInspectiesWpiRoute: typeof AuthenticatedInspectiesWpiRoute
  AuthenticatedInspectiesIndexRoute: typeof AuthenticatedInspectiesIndexRoute
}

const AuthenticatedInspectiesRouteChildren: AuthenticatedInspectiesRouteChildren =
  {
    AuthenticatedInspectiesIdRoute: AuthenticatedInspectiesIdRoute,
    AuthenticatedInspectiesKwaliteitRoute:
      AuthenticatedInspectiesKwaliteitRoute,
    AuthenticatedInspectiesWpiRoute: AuthenticatedInspectiesWpiRoute,
    AuthenticatedInspectiesIndexRoute: AuthenticatedInspectiesIndexRoute,
  }

const AuthenticatedInspectiesRouteWithChildren =
  AuthenticatedInspectiesRoute._addFileChildren(
    AuthenticatedInspectiesRouteChildren,
  )

interface AuthenticatedMeldingenRouteChildren {
  AuthenticatedMeldingenIdRoute: typeof AuthenticatedMeldingenIdRoute
  AuthenticatedMeldingenInternRoute: typeof AuthenticatedMeldingenInternRoute
  AuthenticatedMeldingenOngevallenRoute: typeof AuthenticatedMeldingenOngevallenRoute
  AuthenticatedMeldingenIndexRoute: typeof AuthenticatedMeldingenIndexRoute
}

const AuthenticatedMeldingenRouteChildren: AuthenticatedMeldingenRouteChildren =
  {
    AuthenticatedMeldingenIdRoute: AuthenticatedMeldingenIdRoute,
    AuthenticatedMeldingenInternRoute: AuthenticatedMeldingenInternRoute,
    AuthenticatedMeldingenOngevallenRoute:
      AuthenticatedMeldingenOngevallenRoute,
    AuthenticatedMeldingenIndexRoute: AuthenticatedMeldingenIndexRoute,
  }

const AuthenticatedMeldingenRouteWithChildren =
  AuthenticatedMeldingenRoute._addFileChildren(
    AuthenticatedMeldingenRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedInspectiesRoute: typeof AuthenticatedInspectiesRouteWithChildren
  AuthenticatedMeldingenRoute: typeof AuthenticatedMeldingenRouteWithChildren
  AuthenticatedMosRoute: typeof AuthenticatedMosRoute
  AuthenticatedStopRoute: typeof AuthenticatedStopRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedEmployeesIdRoute: typeof AuthenticatedEmployeesIdRoute
  AuthenticatedToolboxesIdRoute: typeof AuthenticatedToolboxesIdRoute
  AuthenticatedToolboxesNewRoute: typeof AuthenticatedToolboxesNewRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
  AuthenticatedToolboxesIndexRoute: typeof AuthenticatedToolboxesIndexRoute
  AuthenticatedToolboxesSessionsIdRoute: typeof AuthenticatedToolboxesSessionsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedInspectiesRoute: AuthenticatedInspectiesRouteWithChildren,
  AuthenticatedMeldingenRoute: AuthenticatedMeldingenRouteWithChildren,
  AuthenticatedMosRoute: AuthenticatedMosRoute,
  AuthenticatedStopRoute: AuthenticatedStopRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedEmployeesIdRoute: AuthenticatedEmployeesIdRoute,
  AuthenticatedToolboxesIdRoute: AuthenticatedToolboxesIdRoute,
  AuthenticatedToolboxesNewRoute: AuthenticatedToolboxesNewRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  AuthenticatedToolboxesIndexRoute: AuthenticatedToolboxesIndexRoute,
  AuthenticatedToolboxesSessionsIdRoute: AuthenticatedToolboxesSessionsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SignTokenRoute: SignTokenRoute,
  ApiPublicToolboxSignRoute: ApiPublicToolboxSignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
